In [4]:
import pandas as pd
import os
WRK_DIR = "/home/prime/Projets/2026_PROJECT-DA/DATA/EVENTS" #Directoire des fichier evenemenets

In [ ]:
files_names = [] # List of all files names in the directory
files_shape = [] # List of all shapes for each file
files_col = [] # List of all colums name for one files
files_col_nb = [] # List of all numbers of colums for each file

# LOOP FOR EACH FILES
for file in os.listdir(WRK_DIR) : # for each files in the path
  df = pd.read_excel(WRK_DIR + "/" + file) # read the file
  print(f"File {file} is reading") # Debug
  
  files_names.append(file) # Add file name
  files_shape.append(df.shape) # Add file shape
  files_col_nb.append(len(df.columns)) # add number of col

  col = list(df.columns)
  files_col.append(col) # Add list of columns names

# DataFrame creation form a dictionnary
files_infos = {
    "names" : files_names,
    "shape" : files_shape,
    "col_nb" : files_col_nb,
    "col_names" : files_col
}

infos = pd.DataFrame(files_infos)
infos.head() # See df

,names,shape,col_nb,col_names
0,2024-07-28_JO_Rugby-F.xlsx,"(678, 17)",17,"[Code, Matricule, Nom, Prénom, Téléphone, Qual..."
1,2024-08-05_JO_Athletisme.xlsx,"(975, 17)",17,"[Code, Matricule, Nom, Prénom, Téléphone, Qual..."
2,2024-10-01_CONCERT_Mylene-Farmer.xlsx,"(420, 17)",17,"[Code, Matricule, Nom, Prénom, Téléphone, Qual..."
3,2025-06-19_CONCERT_Beyonce.xlsx,"(536, 17)",17,"[Code, Matricule, Nom, Prénom, Téléphone, Qual..."
4,2024-11-14_FOOT_FRA-ISR.xlsx,"(109, 17)",17,"[Code, Matricule, Nom, Prénom, Téléphone, Qual..."

In [6]:
events = pd.DataFrame() # Crée un df vide

for file in os.listdir(WRK_DIR) : # for each files in the path
  df = pd.read_excel(WRK_DIR + "/" + file) # read the file
  print(f"File {file} is reading") # Debug

  df["Event"] = str(file) # Nouvelle colonne nomme par le nom du fichier dans chaque celule

  events = pd.concat([events, df]) # Concatene les df

#display(events.shape)
events.head()

File 2024-07-28_JO_Rugby-F.xlsx is reading
File 2024-08-05_JO_Athletisme.xlsx is reading
File 2024-10-01_CONCERT_Mylene-Farmer.xlsx is reading
File 2025-06-19_CONCERT_Beyonce.xlsx is reading
File 2024-11-14_FOOT_FRA-ISR.xlsx is reading
File 2025-06-21_CONCERT_Beyonce.xlsx is reading
File 2024-08-02_JO_Athletisme.xlsx is reading
File 2025-06-28_RUGBY_TOP14.xlsx is reading
File 2025-03-23_FOOT_FRA-CRO.xlsx is reading
File 2024-09-28_CONCERT_Mylene-Farmer.xlsx is reading
File 2025-04-18_CONCERT_Burna-Boy.xlsx is reading
File 2024-07-27_JO_Rugby-M.xlsx is reading
File 2025-07-11_CONCERT_Linkin-Park.xlsx is reading
File 2024-08-09_JO_Athletisme.xlsx is reading
File 2024-11-16_RUGBY_FRA-NZL.xlsx is reading
File 2024-09-07_JP_Athletisme.xlsx is reading
File 2025-05-24_FOOT_PSG-SDR.xlsx is reading
File 2024-09-08_JP_Athletisme.xlsx is reading
File 2024-08-07_JO_Athletisme.xlsx is reading
File 2024-09-02_JP_Athletisme.xlsx is reading
File 2025-07-27_CONCERT_Stray-Kids.xlsx is reading
File 2025-06-22_CONCERT_Beyonce.xlsx is reading
File 2025-07-26_CONCERT_Stray-Kids.xlsx is reading
File 2024-09-06_JP_Athletisme.xlsx is reading
File 2024-09-03_JP_Athletisme.xlsx is reading
File 2024-07-24_JO_Rugby-M.xlsx is reading
File 2024-09-01_JP_Athletisme.xlsx is reading
File 2025-08-03_CONCERT_BlackPink.xlsx is reading
File 2024-08-03_JO_Athletisme.xlsx is reading
File 2025-04-26_CONCERT_Jul.xlsx is reading
File 2025-05-02_CONCERT_Ninho.xlsx is reading
File 2025-01-31_RUGBY_FRA-WAL.xlsx is reading
File 2024-08-04_JO_Athletisme.xlsx is reading
File 2025-07-05_CONCERT_Imagine-Dragons.xlsx is reading
File 2025-08-13_CONCERT_ACDC.xlsx is reading
File 2024-11-09_RUGBY_FRA-JAP.xlsx is reading
File 2024-09-04_JP_Athletisme.xlsx is reading
File 2025-03-15_RUGBY_FRA-SCT.xlsx is reading
File 2025-08-02_CONCERT_BlackPink.xlsx is reading
File 2025-08-09_CONCERT_ACDC.xlsx is reading
File 2025-07-06_CONCERT_Imagine-Dragons.xlsx is reading
File 2024-08-08_JO_Athletisme.xlsx is reading
File 2024-08-30_JP_Athletisme.xlsx is reading
File 2024-08-31_JP_Athletisme.xlsx is reading
File 2024-09-05_JP_Athletisme.xlsx is reading
File 2025-05-03_CONCERT_Ninho.xlsx is reading
File 2024-08-06_JO_Athletisme.xlsx is reading
File 2025-05-10_CONCERT_DJ-Snake.xlsx is reading
File 2024-08-11_JO_Athletisme.xlsx is reading
File 2024-08-10_JO_Athletisme.xlsx is reading
File 2024-07-25_JO_Rugby-M.xlsx is reading
File 2024-07-29_JO_Rugby-F.xlsx is reading
File 2024-11-22_RUGBY_FRA-ARG.xlsx is reading
File 2024-09-27_CONCERT_Mylene-Farmer.xlsx is reading
File 2024-07-30_JO_Rugby-F.xlsx is reading

,Code,Matricule,Nom,Prénom,Téléphone,Qualification,Equipe,Heure de convocation,Blacklist,Passage exterieur,Passage accred,Passage vestiaire,Prise de poste,Fin de poste,Temps travaillé,Lieu de prise de poste,Lieu de fin de poste,Event
0,82929|a539fb6bb248d168,38859,CISSE,Oumar,33638033860,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,28-07-2024 11:59:26,0,28-07-2024 12:17:46,28-07-2024 14:32:55,28-07-2024 22:37:41,07:34:46,B605,B605,2024-07-28_JO_Rugby-F.xlsx
1,83104|1e35386face21ade,38903,HOU,Jerome Wei,33783012177,MANAGER POINT DE VENTE,2- BAR EST IN,11:00,FAUX,28-07-2024 11:04:21,0,28-07-2024 11:22:02,28-07-2024 11:36:04,0,0,LOGE 1,NaN,2024-07-28_JO_Rugby-F.xlsx
2,84591|d2e6d7cde2df98b8,39423,DRAME,Sokhna,33635502833,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,28-07-2024 10:43:26,0,28-07-2024 10:54:53,0,0,0,NaN,NaN,2024-07-28_JO_Rugby-F.xlsx
3,93097|f39f9bcc50a3ff7f,42702,HALL,Eryne,33783831175,PREPARATEUR POINT DE VENTE,2- BAR EST IN,11:00,FAUX,28-07-2024 10:35:29,0,28-07-2024 10:48:44,0,0,0,NaN,NaN,2024-07-28_JO_Rugby-F.xlsx
4,96761|56d8ae051dc42b2c,44431,AMISI,Honorine,33783236753,MANAGER POINT DE VENTE,2- BAR NORD OUEST IN,11:00,FAUX,28-07-2024 11:10:31,0,28-07-2024 11:20:22,28-07-2024 11:27:47,28-07-2024 22:45:07,10:47:20,LOGE 3,LOGE 3,2024-07-28_JO_Rugby-F.xlsx

In [8]:
events.to_csv("/home/prime/Projets/2026_PROJECT-DA/DATA/events.csv")